import XCTest
import RootstockCore
@testable import MacEnumKit

enum P0CollectorTestFixtures {
    static let wave16Collectors: [any Collector] = [
        AirplayReceiverSurfaceCollector(), HandoffClipboardDepthCollector(), ImessagePathPlaneCollector(),
        FacetimeCameraSurfaceCollector(), FinderSyncExtensionCollector(), FileproviderDomainCollector(),
        NotificationCenterDepthCollector(), SiriSuggestionsPlaneCollector(), SpotlightImporterDepthCollector(),
        ContactsPathPlaneCollector(), CalendarServerPathCollector(), RemindersCloudPathCollector(),
        MapsLocationPathCollector(), WeatherWidgetPathCollector(), MusicLibraryPathCollector(),
        BooksPathPlaneCollector(), PodcastsPathPlaneCollector(), TvAppPathPlaneCollector(),
        HomekitPathPlaneCollector(), HealthPathPlaneCollector(), WalletPassPathCollector(),
        FindmyPathPlaneCollector(), ShortcutsIcloudSyncCollector(), DevicemanagementProfileCollector(),
        SoftwareupdateCatalogCollector(),
    ]

    static let wave16CollectorIDs = [
        "collect.airplay_receiver_surface", "collect.handoff_clipboard_depth", "collect.imessage_path_plane",
        "collect.facetime_camera_surface", "collect.finder_sync_extension", "collect.fileprovider_domain",
        "collect.notification_center_depth", "collect.siri_suggestions_plane", "collect.spotlight_importer_depth",
        "collect.contacts_path_plane", "collect.calendar_server_path", "collect.reminders_cloud_path",
        "collect.maps_location_path", "collect.weather_widget_path", "collect.music_library_path",
        "collect.books_path_plane", "collect.podcasts_path_plane", "collect.tv_app_path_plane",
        "collect.homekit_path_plane", "collect.health_path_plane", "collect.wallet_pass_path",
        "collect.findmy_path_plane", "collect.shortcuts_icloud_sync", "collect.devicemanagement_profile",
        "collect.softwareupdate_catalog",
    ]

    static let requiredCollectorIDs = [
        "collect.protections",
        "collect.loginitems_btm",
        "collect.browser_meta",
        "collect.dylib_risk",
        "collect.injectability",
        "collect.codesign",
        "collect.network",
        "collect.tcc_graph",
        "collect.loobins",
        "collect.security_products",
        "collect.esf_endpoint_security",
        "collect.patch_debt",
        "collect.tcc_permission_graph",
        "collect.launch_constraints",
        "collect.network_extension",
        "collect.auth_rights",
        "collect.developer_toolchain",
        "collect.time_machine",
        "collect.config_profile_sideload",
        "collect.app_sandbox_entitlements",
        "collect.notarization_stapling",
        "collect.virtualization_containers",
        "collect.continuity_airdrop",
        "collect.filevault_escrow",
        "collect.clickfix_terminal_delivery",
        "collect.remote_apple_events",
        "collect.spotlight_ai_cache",
        "collect.security_mgmt_plane",
        "collect.third_party_tcc_inheritance",
        "collect.ssh_agent_key_path",
        "collect.packagekit_installer_design",
        "collect.archive_quarantine_extractor",
        "collect.infostealer_path_plane",
        "collect.tcc_esf_visibility_depth",
        "collect.mdm_profile_parse_depth",
        "collect.url_scheme_handler",
        "collect.launchd_override_depth",
        "collect.browser_extension_dualuse",
        "collect.shortcuts_app_intents",
        "collect.webloc_inetloc_delivery",
        "collect.mail_rules_automation",
        "collect.unified_log_observation",
        "collect.dock_persistence_surface",
        "collect.osascript_scpt_delivery",
        "collect.network_share_mount",
        "collect.calendar_reminders_automation",
        "collect.gatekeeper_assessment_history",
        "collect.homebrew_package_dualuse",
        "collect.cups_print_dualuse",
        "collect.screencapture_privacy_dualuse",
        "collect.automator_workflow",
        "collect.icloud_drive_path",
        "collect.bluetooth_continuity_depth",
        "collect.font_validation_dualuse",
        "collect.quicklook_cache_depth",
        "collect.dns_resolver_dualuse",
        "collect.ls_quarantine_db_depth",
        "collect.pam_auth_module",
        "collect.cron_at_job_depth",
        "collect.notes_metadata_plane",
        "collect.photos_library_path",
        "collect.vpn_config_dualuse",
        "collect.sandbox_container_depth",
        "collect.xpc_mach_service_depth",
        "collect.tm_local_snapshot_depth",
        "collect.emond_legacy_depth",
        "collect.screen_sharing_ard_depth",
        "collect.keychain_acl_path",
        "collect.python_runtime_dualuse",
        "collect.shell_plugin_manager",
        "collect.airplay_receiver_surface",
        "collect.handoff_clipboard_depth",
        "collect.imessage_path_plane",
        "collect.facetime_camera_surface",
        "collect.finder_sync_extension",
        "collect.fileprovider_domain",
        "collect.notification_center_depth",
        "collect.siri_suggestions_plane",
        "collect.spotlight_importer_depth",
        "collect.contacts_path_plane",
        "collect.calendar_server_path",
        "collect.reminders_cloud_path",
        "collect.maps_location_path",
        "collect.weather_widget_path",
        "collect.music_library_path",
        "collect.books_path_plane",
        "collect.podcasts_path_plane",
        "collect.tv_app_path_plane",
        "collect.homekit_path_plane",
        "collect.health_path_plane",
        "collect.wallet_pass_path",
        "collect.findmy_path_plane",
        "collect.shortcuts_icloud_sync",
        "collect.devicemanagement_profile",
        "collect.softwareupdate_catalog",
    ]
}
