strict: true
check_for_updates: false

included:
  - collector/Sources
  - packages/RootstockMacFacts/Sources
  - rootstock-red/Sources
  - rootstock-blue/Sources

excluded:
  - "**/.build/**"
  - "**/Generated/**"

only_rules:
  - cyclomatic_complexity
  - deployment_target
  - duplicate_conditions
  - duplicate_enum_cases
  - function_body_length
  - identical_operands
  - overridden_super_call
  - unneeded_break_in_switch
  - unowned_variable_capture
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding

cyclomatic_complexity: 8
function_body_length: 60
